import { Router } from 'express'
import type { Request, Response } from 'express'

const router = Router()

const API_DOCS = {
  title: 'Gestor App — API Reference',
  version: '1',
  baseUrl: '/api',
  note: 'All /api/v1/* endpoints require a Bearer JWT token in the Authorization header unless noted otherwise.',
  sections: {
    auth: {
      description: 'Authentication — register, login, password reset, and session management.',
      endpoints: [
        {
          method: 'POST',
          path: '/api/auth/register',
          description: 'Register a new account. Newly created accounts are inactive until an admin approves them.',
          auth: false,
          body: { email: 'string (required)', password: 'string ≥8 chars (required)', name: 'string (optional)' },
          responses: { 201: '{ ok: true, pending: true }', 400: 'Validation error', 409: 'Email already registered' },
        },
        {
          method: 'POST',
          path: '/api/auth/login',
          description: 'Log in with email and password. Returns a JWT token valid for the configured JWT_EXPIRY period (default 7d).',
          auth: false,
          body: { email: 'string (required)', password: 'string (required)' },
          responses: { 200: '{ token, user: { id, email, name, role, avatarUrl } }', 401: 'Invalid credentials', 429: 'Too many failed attempts' },
        },
        {
          method: 'GET',
          path: '/api/auth/me',
          description: 'Return the authenticated user\'s profile.',
          auth: true,
          responses: { 200: '{ user: { id, email, name, role, avatarUrl } }', 401: 'Missing/invalid token' },
        },
        {
          method: 'POST',
          path: '/api/auth/logout',
          description: 'Stateless logout — invalidates nothing server-side. Clear the token client-side.',
          auth: false,
          responses: { 200: '{ ok: true }' },
        },
        {
          method: 'POST',
          path: '/api/auth/forgot-password',
          description: 'Request a password-reset link via email. Always returns 200 to prevent email enumeration.',
          auth: false,
          body: { email: 'string (required)' },
          responses: { 200: '{ ok: true }' },
        },
        {
          method: 'POST',
          path: '/api/auth/reset-password',
          description: 'Consume a password-reset token and set a new password.',
          auth: false,
          body: { token: 'string (required)', password: 'string ≥8 chars (required)' },
          responses: { 200: '{ ok: true }', 400: 'Invalid or expired token' },
        },
        {
          method: 'POST',
          path: '/api/auth/change-password',
          description: 'Change the current user\'s password.',
          auth: true,
          body: { currentPassword: 'string (required)', newPassword: 'string ≥8 chars (required)' },
          responses: { 200: '{ ok: true }', 401: 'Wrong current password' },
        },
      ],
    },

    movements: {
      description: 'Financial movements (income, expense, transfer). Soft-deleted. Scoped to authenticated user.',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/movements',
          description: 'List movements for the authenticated user with pagination and filters.',
          auth: true,
          query: {
            limit: 'number (default 50, max 500)',
            offset: 'number (default 0)',
            startDate: 'YYYY-MM-DD',
            endDate: 'YYYY-MM-DD',
            kind: 'income | expense | transfer_in | transfer_out',
            status: 'confirmed | pending',
            orgId: 'UUID — filter to an organisation',
            personal: 'true — exclude org movements',
          },
          responses: { 200: '{ data: Movement[], total, limit, offset }' },
        },
        {
          method: 'GET',
          path: '/api/v1/movements/:id',
          description: 'Fetch a single movement by ID.',
          auth: true,
          responses: { 200: '{ data: Movement }', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/movements',
          description: 'Create a movement.',
          auth: true,
          body: {
            account_id: 'UUID (required)',
            date: 'YYYY-MM-DD (required)',
            kind: 'income | expense (required)',
            amount: 'number > 0 (required)',
            description: 'string ≤500 (optional)',
            category_id: 'UUID (optional)',
            organization_id: 'UUID (optional)',
            status: 'confirmed | pending (optional)',
          },
          responses: { 201: '{ data: Movement }', 400: 'Validation error' },
        },
        {
          method: 'POST',
          path: '/api/v1/movements/transfer',
          description: 'Create a transfer between two accounts (generates a transfer_out + transfer_in pair atomically).',
          auth: true,
          body: {
            from_account_id: 'UUID (required)',
            to_account_id: 'UUID (required)',
            amount: 'number > 0 (required)',
            date: 'YYYY-MM-DD (required)',
            description: 'string ≤500 (optional)',
            org_id: 'UUID (optional)',
          },
          responses: { 201: '{ data: { out: Movement, in: Movement } }', 400: 'Validation error', 404: 'Account not found' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/movements/:id',
          description: 'Partially update a movement.',
          auth: true,
          body: 'Subset of movement fields',
          responses: { 200: '{ data: Movement }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/movements/:id',
          description: 'Soft-delete a movement (sets deleted_at).',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    accounts: {
      description: 'Financial accounts (bank accounts, wallets, cash, etc.). Scoped to user or organisation.',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/accounts',
          description: 'List accounts. Pass org_id to list org accounts.',
          auth: true,
          query: { org_id: 'UUID (optional)', limit: 'number (default 200)', offset: 'number' },
          responses: { 200: '{ data: Account[], total, limit, offset }' },
        },
        {
          method: 'GET',
          path: '/api/v1/accounts/:id',
          description: 'Fetch a single account.',
          auth: true,
          responses: { 200: '{ data: Account }', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/accounts',
          description: 'Create an account.',
          auth: true,
          body: {
            name: 'string ≤150 (required)',
            type: 'string (optional, default "general")',
            currency: 'string (optional, default "EUR")',
            balance: 'number (optional, default 0)',
            description: 'string ≤500 (optional)',
            color: 'string (optional)',
            icon: 'string (optional)',
            is_active: 'boolean (optional, default true)',
            parent_account_id: 'UUID (optional)',
            organization_id: 'UUID (optional)',
          },
          responses: { 201: '{ data: Account }', 409: 'Duplicate name' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/accounts/:id',
          description: 'Partially update an account.',
          auth: true,
          body: 'Subset of account fields',
          responses: { 200: '{ data: Account }', 404: 'Not found', 409: 'Duplicate name' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/accounts/:id',
          description: 'Soft-delete an account.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    categories: {
      description: 'Expense/income categories. Scoped to user or organisation.',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/categories',
          description: 'List categories. Pass org_id to list org categories.',
          auth: true,
          query: { org_id: 'UUID (optional)', kind: 'income | expense (optional)', limit: 'number', offset: 'number' },
          responses: { 200: '{ data: Category[], total, limit, offset }' },
        },
        {
          method: 'GET',
          path: '/api/v1/categories/:id',
          description: 'Fetch a single category.',
          auth: true,
          responses: { 200: '{ data: Category }', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/categories',
          description: 'Create a category.',
          auth: true,
          body: {
            name: 'string ≤100 (required)',
            kind: 'income | expense (required)',
            color: 'string (optional)',
            icon: 'string (optional)',
            organization_id: 'UUID (optional)',
          },
          responses: { 201: '{ data: Category }', 409: 'Duplicate name' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/categories/:id',
          description: 'Partially update a category.',
          auth: true,
          responses: { 200: '{ data: Category }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/categories/:id',
          description: 'Soft-delete a category.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    recurring: {
      description: 'Recurring rules that auto-generate movements on a schedule (daily, weekly, monthly, etc.).',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/recurring-rules',
          description: 'List recurring rules for the authenticated user.',
          auth: true,
          query: { org_id: 'UUID (optional)', limit: 'number', offset: 'number' },
          responses: { 200: '{ data: RecurringRule[], total, limit, offset }' },
        },
        {
          method: 'GET',
          path: '/api/v1/recurring-rules/:id',
          description: 'Fetch a single recurring rule.',
          auth: true,
          responses: { 200: '{ data: RecurringRule }', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/recurring-rules',
          description: 'Create a recurring rule.',
          auth: true,
          body: {
            kind: 'income | expense (required)',
            amount: 'number > 0 (required)',
            frequency: 'daily | weekly | monthly | yearly (required)',
            account_id: 'UUID (required)',
            description: 'string ≤500 (optional)',
            category_id: 'UUID (optional)',
            next_occurrence: 'YYYY-MM-DD (optional)',
            day_of_week: 'number 0–6 (optional, for weekly)',
            day_of_month: 'number 1–31 (optional, for monthly)',
            auto_apply: 'boolean (optional)',
            is_active: 'boolean (optional, default true)',
            organization_id: 'UUID (optional)',
          },
          responses: { 201: '{ data: RecurringRule }', 400: 'Validation error' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/recurring-rules/:id',
          description: 'Partially update a recurring rule.',
          auth: true,
          responses: { 200: '{ data: RecurringRule }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/recurring-rules/:id',
          description: 'Soft-delete a recurring rule.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    budgets: {
      description: 'Monthly spending budgets per category.',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/budgets',
          description: 'List budgets for the authenticated user.',
          auth: true,
          query: { month: 'YYYY-MM (optional)', org_id: 'UUID (optional)', limit: 'number', offset: 'number' },
          responses: { 200: '{ data: Budget[], total, limit, offset }' },
        },
        {
          method: 'GET',
          path: '/api/v1/budgets/:id',
          description: 'Fetch a single budget.',
          auth: true,
          responses: { 200: '{ data: Budget }', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/budgets',
          description: 'Create a monthly budget.',
          auth: true,
          body: {
            categoryName: 'string ≤120 (required)',
            monthlyLimit: 'number ≥0 (required)',
            month: 'YYYY-MM (optional)',
            organization_id: 'UUID (optional)',
          },
          responses: { 201: '{ data: Budget }', 409: 'Budget already exists for this category/month' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/budgets/:id',
          description: 'Update a budget.',
          auth: true,
          responses: { 200: '{ data: Budget }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/budgets/:id',
          description: 'Delete a budget.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    alerts: {
      description: 'Notification alerts and configurable alert rules (threshold triggers, etc.).',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/alerts',
          description: 'List alerts for the authenticated user.',
          auth: true,
          query: { unread: 'true — filter to unread only', limit: 'number', offset: 'number' },
          responses: { 200: '{ data: Alert[], total, limit, offset }' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/alerts/:id/read',
          description: 'Mark an alert as read.',
          auth: true,
          responses: { 200: '{ data: Alert }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/alerts/:id',
          description: 'Delete an alert.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
        {
          method: 'GET',
          path: '/api/v1/alert-rules',
          description: 'List alert rules for the authenticated user.',
          auth: true,
          responses: { 200: '{ data: AlertRule[], total, limit, offset }' },
        },
        {
          method: 'POST',
          path: '/api/v1/alert-rules',
          description: 'Create an alert rule.',
          auth: true,
          body: {
            type: 'budget_exceeded | large_expense | low_balance | custom (required)',
            threshold: 'number (required)',
            category_id: 'UUID (optional)',
            is_active: 'boolean (optional, default true)',
            trigger_mode: 'once | repeat (optional, default "repeat")',
          },
          responses: { 201: '{ data: AlertRule }', 400: 'Validation error' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/alert-rules/:id',
          description: 'Update an alert rule.',
          auth: true,
          responses: { 200: '{ data: AlertRule }', 404: 'Not found' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/alert-rules/:id',
          description: 'Delete an alert rule.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Not found' },
        },
      ],
    },

    organizations: {
      description: 'Organisations for shared/business finance. Members have roles: owner | admin | member | viewer.',
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/organizations',
          description: 'List organisations the authenticated user belongs to.',
          auth: true,
          responses: { 200: '{ data: Organization[] }' },
        },
        {
          method: 'GET',
          path: '/api/v1/organizations/:id',
          description: 'Fetch a single organisation.',
          auth: true,
          responses: { 200: '{ data: Organization }', 403: 'Not a member', 404: 'Not found' },
        },
        {
          method: 'POST',
          path: '/api/v1/organizations',
          description: 'Create an organisation. The creator becomes the owner.',
          auth: true,
          body: {
            name: 'string ≤150 (required)',
            slug: 'string ≤80 a-z0-9- (optional)',
            description: 'string ≤500 (optional)',
            parentId: 'UUID (optional)',
          },
          responses: { 201: '{ data: Organization }', 409: 'Slug already taken' },
        },
        {
          method: 'PATCH',
          path: '/api/v1/organizations/:id',
          description: 'Update organisation details. Requires admin or owner role.',
          auth: true,
          responses: { 200: '{ data: Organization }', 403: 'Insufficient role' },
        },
        {
          method: 'DELETE',
          path: '/api/v1/organizations/:id',
          description: 'Delete an organisation. Requires owner role.',
          auth: true,
          responses: { 200: '{ ok: true }', 403: 'Insufficient role' },
        },
        {
          method: 'GET',
          path: '/api/v1/organizations/:id/members',
          description: 'List members of an organisation.',
          auth: true,
          responses: { 200: '{ data: Member[] }', 403: 'Not a member' },
        },
        {
          method: 'POST',
          path: '/api/v1/organizations/:id/invitations',
          description: 'Invite a user to an organisation by email.',
          auth: true,
          body: { email: 'string (required)', role: 'admin | member | viewer (optional, default "member")' },
          responses: { 201: '{ data: Invitation }', 403: 'Insufficient role' },
        },
        {
          method: 'POST',
          path: '/api/v1/organizations/:id/invitations/:token/accept',
          description: 'Accept an organisation invitation.',
          auth: true,
          responses: { 200: '{ ok: true }', 404: 'Invalid or expired invitation' },
        },
      ],
    },
  },
}

// GET /api/docs
router.get('/', (_req: Request, res: Response) => {
  res.json(API_DOCS)
})

export default router
